feat: Allow controlling sidecar environment variables
sysdiglabs/agent-kilt pull request #12
Opened 2023-11-27 10:34 UTC by gnosek

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area tests

> /area proposals

**What this PR does / why we need it**:

Without this PR, the injected sidecars are pretty much forced to run with the default environment. This PR introduces two ways to control the sidecar environment:

1. Any changes to the environment in the top-level environment_variables section are propagated to sidecars
2. Each sidecar (mount section in the config) can have its own private environment variables that take preference over the top-level ones

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

This is https://github.com/falcosecurity/kilt/pull/81, resubmitted without changes

2023-11-27 11:45 UTC, pgcrooks-sysdig requested changes
Hopefully the renames will unblock the tests.

2023-11-27 11:45 UTC, pgcrooks-sysdig commented on pkg/hocon/task.go
> +	"github.com/falcosecurity/kilt/pkg/kilt"
Does this need updated to `agent-kilt`?

2023-11-27 11:45 UTC, pgcrooks-sysdig commented on runtimes/cloudformation/go.mod
> +replace github.com/falcosecurity/kilt/pkg => ../../pkg
```suggestion
replace github.com/agent-kilt/kilt/pkg => ../../pkg
```

Or something similar?

2023-11-27 11:46 UTC, gnosek commented
Working on these right now. Yeah, something like this.

2023-11-27 17:49 UTC, francesco-racciatti approved these changes
lgtm

2023-11-28 08:46 UTC, pgcrooks-sysdig approved these changes
LGTM

2023-12-07 11:03 UTC, merged